import { OnChanges, OnInit, OnDestroy } from '@angular/core';
import { TdChartOptionsService } from '../base.service';
export declare abstract class TdChartAxisComponent implements OnChanges, OnInit, OnDestroy {
    private _axisOption;
    private _optionsService;
    private _state;
    config: any;
    id: string;
    show: boolean;
    gridIndex: number;
    offset: number;
    abstract position: any;
    type: 'category' | 'value' | 'time' | 'logs';
    name: string;
    nameLocation: 'start' | 'middle' | 'center' | 'end';
    nameTextStyle: any;
    nameGap: number;
    nameRotate: number;
    inverse: boolean;
    boundaryGap: boolean | string[];
    min: string | number;
    max: string | number;
    scale: boolean;
    minInterval: number;
    interval: number;
    logBase: number;
    silent: boolean;
    triggerEvent: boolean;
    axisLine: any;
    axisTick: any;
    axisLabel: any;
    splitLine: any;
    splitArea: any;
    data: any;
    axisPointer: any;
    zlevel: number;
    z: number;
    constructor(_axisOption: string, _optionsService: TdChartOptionsService);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    private _setOptions();
    private _removeOption();
}
