import { OnChanges, OnInit, OnDestroy } from '@angular/core';
import 'echarts/lib/chart/bar';
import { TdChartOptionsService, TdCoordinateSystem, ITdItemStyle, ITdEmphasis, TdSeriesLayoutBy, ITdMarkPoint, ITdMarkLine, ITdMarkArea, ITdSeriesTooltip } from '@covalent/echarts/base';
export declare class TdChartSeriesBarComponent implements OnChanges, OnInit, OnDestroy {
    private _optionsService;
    private _type;
    private _state;
    config: any;
    id: string;
    name: string;
    color: string;
    coordinateSystem: TdCoordinateSystem;
    xAxisIndex: number;
    yAxisIndex: number;
    legendHoverLink: boolean;
    stack: string;
    cursor: string;
    label: any;
    itemStyle: ITdItemStyle;
    emphasis: ITdEmphasis;
    barWidth: number;
    barMaxWidth: number;
    barMinHeight: number;
    barGap: string;
    barCategoryGap: string;
    large: boolean;
    largeThreshold: number;
    progressive: number;
    progressiveThreshold: number;
    progressiveChunkMode: string;
    dimensions: any[];
    encode: any;
    seriesLayoutBy: TdSeriesLayoutBy;
    datasetIndex: number;
    data: any[];
    markPoint: ITdMarkPoint;
    markLine: ITdMarkLine;
    markArea: ITdMarkArea;
    zlevel: number;
    z: number;
    animation: boolean;
    animationThreshold: number;
    animationDuration: number | Function;
    animationEasing: string;
    animationDelay: number | Function;
    animationDurationUpdate: number | Function;
    animationEasingUpdate: string;
    animationDelayUpdate: number | Function;
    tooltip: ITdSeriesTooltip;
    constructor(_optionsService: TdChartOptionsService);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    private _setOptions();
    private _removeOption();
}
