import { OnChanges, OnInit, OnDestroy } from '@angular/core';
import 'echarts/lib/chart/line';
import { TdChartOptionsService, TdCoordinateSystem, TdMarkPointSymbol, ITdLabel, ITdItemStyle, ITdLineStyle, ITdAreaStyle, TdSeriesLayoutBy, ITdMarkPoint, ITdMarkLine, ITdMarkArea, ITdSeriesTooltip, ITdEmphasis } from '@covalent/echarts/base';
import { ITdLineConfig } from './line-config.interface';
export declare class TdChartSeriesLineComponent implements OnChanges, OnInit, OnDestroy {
    private _optionsService;
    private _type;
    private _state;
    config: ITdLineConfig;
    id: string;
    name: string;
    color: string;
    coordinateSystem: TdCoordinateSystem;
    xAxisIndex: number;
    yAxisIndex: number;
    polarIndex: number;
    symbol: TdMarkPointSymbol | string;
    symbolSize: number | any[] | Function;
    symbolRotate: number;
    symbolKeepAspect: boolean;
    symbolOffset: any[];
    showSymbol: boolean;
    showAllSymbol: boolean;
    hoverAnimation: boolean;
    legendHoverLink: boolean;
    stack: string;
    cursor: string;
    connectNulls: boolean;
    clipOverflow: boolean;
    step: string | boolean;
    label: ITdLabel;
    itemStyle: ITdItemStyle;
    lineStyle: ITdLineStyle;
    areaStyle: ITdAreaStyle;
    emphasis: ITdEmphasis;
    smooth: boolean | number;
    smoothMonotone: string;
    sampling: string;
    dimensions: any[];
    encode: any;
    seriesLayoutBy: TdSeriesLayoutBy;
    datasetIndex: number;
    data: any[];
    markPoint: ITdMarkPoint;
    markLine: ITdMarkLine;
    markArea: ITdMarkArea;
    zlevel: number;
    z: number;
    silent: boolean;
    animation: boolean;
    animationThreshold: number;
    animationDuration: number | Function;
    animationEasing: string;
    animationDelay: number | Function;
    animationDurationUpdate: number | Function;
    animationEasingUpdate: string;
    animationDelayUpdate: number | Function;
    tooltip: ITdSeriesTooltip;
    constructor(_optionsService: TdChartOptionsService);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    private _setOptions();
    private _removeOption();
}
