import { OnChanges, OnInit, OnDestroy } from '@angular/core';
import 'echarts/lib/chart/line';
import { TdChartOptionsService } from '@covalent/echarts/base';
export declare class TdChartSeriesLineComponent implements OnChanges, OnInit, OnDestroy {
    private _optionsService;
    private _type;
    private _state;
    config: any;
    id: string;
    type: string;
    name: string;
    coordinateSystem: string;
    xAxisIndex: number;
    yAxisIndex: number;
    polarIndex: number;
    symbol: string;
    symbolSize: number | any[] | Function;
    symbolRotate: number;
    symbolKeepAspect: boolean;
    symbolOffset: any[];
    showSymbol: boolean;
    showAllSymbol: boolean;
    hoverAnimation: boolean;
    legendHoverLink: boolean;
    stack: string;
    cursor: string;
    connectNulls: boolean;
    clipOverflow: boolean;
    step: string | boolean;
    label: any;
    itemStyle: any;
    lineStyle: any;
    areaStyle: any;
    emphasis: any;
    smooth: boolean | number;
    smoothMonotone: string;
    sampling: string;
    dimensions: any[];
    encode: any;
    seriesLayoutBy: string;
    datasetIndex: number;
    data: any[];
    markPoint: any;
    markLine: any;
    markArea: any;
    zlevel: number;
    z: number;
    silent: boolean;
    animation: boolean;
    animationThreshold: number;
    animationDuration: number | Function;
    animationEasing: string;
    animationDelay: number | Function;
    animationDurationUpdate: number | Function;
    animationEasingUpdate: string;
    animationDelayUpdate: number | Function;
    tooltip: any;
    constructor(_optionsService: TdChartOptionsService);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    private _setOptions();
    private _removeOption();
}
