import { EventEmitter, ElementRef, ChangeDetectorRef, AfterViewInit, OnChanges, OnDestroy, DoCheck } from '@angular/core';
import 'echarts/lib/component/title';
import 'echarts/lib/component/legend';
import 'echarts/lib/component/legendScroll';
import 'echarts/lib/component/markArea';
import 'echarts/lib/component/dataZoom';
import { TdChartOptionsService } from './base.service';
export declare class TdBaseChartComponent implements AfterViewInit, OnChanges, DoCheck, OnDestroy {
    private _changeDetectorRef;
    private _elementRef;
    private _optionsService;
    private _resizeSubscription;
    private _widthSubject;
    private _heightSubject;
    private _resizing;
    private _series;
    private _legend;
    private _instance;
    private _options;
    readonly instance: any;
    readonly options: any;
    chartTitle: string;
    showLegend: boolean;
    data: any[];
    max: number;
    chartGroup: string;
    dataZoom: boolean;
    markAreaClick: EventEmitter<any>;
    constructor(_changeDetectorRef: ChangeDetectorRef, _elementRef: ElementRef, _optionsService: TdChartOptionsService);
    ngAfterViewInit(): void;
    ngDoCheck(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    render(): void;
}
