import { EventEmitter, ElementRef, ChangeDetectorRef, AfterViewInit, OnChanges, NgZone, OnDestroy, DoCheck } from '@angular/core';
import 'echarts/lib/chart/line';
import 'echarts/lib/chart/bar';
import 'echarts/lib/component/tooltip';
import 'echarts/lib/component/title';
import 'echarts/lib/component/legend';
import 'echarts/lib/component/legendScroll';
import 'echarts/lib/component/markArea';
import 'echarts/lib/component/dataZoom';
export declare class TdChartComponent implements AfterViewInit, OnChanges, DoCheck, OnDestroy {
    private _changeDetectorRef;
    private _elementRef;
    private _ngZone;
    private _resizeSubscription;
    private _widthSubject;
    private _heightSubject;
    private _resizing;
    private _series;
    private _legend;
    private _instance;
    readonly instance: any;
    chartTitle: string;
    showLegend: boolean;
    showTooltip: boolean;
    data: any[];
    max: number;
    chartGroup: string;
    yAxisFormatter: (value: any, index?: number) => string;
    xAxisFormatter: (value: any, index?: number) => string;
    yAxisType: string;
    xAxisType: string;
    dataZoom: boolean;
    tooltipFormatter: (params: any, ticket?: string, callback?: (ticket: string, html: string) => any) => string;
    xAxis: any[];
    yAxis: any[];
    showXAxis: boolean;
    showYAxis: boolean;
    yAxisSplitNumber: number;
    markAreaClick: EventEmitter<any>;
    constructor(_changeDetectorRef: ChangeDetectorRef, _elementRef: ElementRef, _ngZone: NgZone);
    ngAfterViewInit(): void;
    ngDoCheck(): void;
    ngOnChanges(): void;
    ngOnDestroy(): void;
    render(): void;
}
